"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""


from setuptools import setup

APP = ['PyInvaders.py']
DATA_FILES = ["lib.py","classes.py","functions.py","leaderboard.txt","data"]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
